ALTER TABLE gas_fee_deposits
  ADD COLUMN IF NOT EXISTS network TEXT NOT NULL DEFAULT 'BEP-20',
  ADD COLUMN IF NOT EXISTS chain_id INTEGER NOT NULL DEFAULT 56,
  ADD COLUMN IF NOT EXISTS token_contract TEXT NOT NULL DEFAULT '0x55d398326f99059ff775485246999027b3197955',
  ADD COLUMN IF NOT EXISTS sender_address TEXT,
  ADD COLUMN IF NOT EXISTS block_number BIGINT,
  ADD COLUMN IF NOT EXISTS confirmations INTEGER,
  ADD COLUMN IF NOT EXISTS actual_amount NUMERIC(36,18),
  ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS verification_note TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_gas_fee_deposits_tx_id_status
  ON gas_fee_deposits (tx_id, status)
  WHERE tx_id IS NOT NULL AND tx_id <> '';
